[profile.default]
src = "src/Contracts"
out = "out"
libs = ["lib"]
verbosity = 5
fs_permissions = [{ access = "read-write", path = "./"}]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
